apiVersion: client.authentication.k8s.io/v1alpha1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  selector:
    matchLabels:
        app: java-app
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: hadeelharidy/javaapp:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always